version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - touch-grass-network
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - touch-grass-network
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - touch-grass-network

networks:
  touch-grass-network:
    driver: bridge

volumes:
  mongo-data: